/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Alert_LED */
#define Alert_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_0_INBUF_ENABLED 0u
#define Alert_LED_0_INIT_DRIVESTATE 1u
#define Alert_LED_0_INIT_MUXSEL 0u
#define Alert_LED_0_INPUT_SYNC 2u
#define Alert_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_0_NUM 1u
#define Alert_LED_0_PORT GPIO_PRT11
#define Alert_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Alert_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_INBUF_ENABLED 0u
#define Alert_LED_INIT_DRIVESTATE 1u
#define Alert_LED_INIT_MUXSEL 0u
#define Alert_LED_INPUT_SYNC 2u
#define Alert_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_NUM 1u
#define Alert_LED_PORT GPIO_PRT11
#define Alert_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_DEBUG_rx */
#define UART_DEBUG_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_DEBUG_rx_0_INBUF_ENABLED 1u
#define UART_DEBUG_rx_0_INIT_DRIVESTATE 1u
#define UART_DEBUG_rx_0_INIT_MUXSEL 18u
#define UART_DEBUG_rx_0_INPUT_SYNC 2u
#define UART_DEBUG_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_rx_0_NUM 0u
#define UART_DEBUG_rx_0_PORT GPIO_PRT5
#define UART_DEBUG_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_DEBUG_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_DEBUG_rx_INBUF_ENABLED 1u
#define UART_DEBUG_rx_INIT_DRIVESTATE 1u
#define UART_DEBUG_rx_INIT_MUXSEL 18u
#define UART_DEBUG_rx_INPUT_SYNC 2u
#define UART_DEBUG_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_rx_NUM 0u
#define UART_DEBUG_rx_PORT GPIO_PRT5
#define UART_DEBUG_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_DEBUG_tx */
#define UART_DEBUG_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_DEBUG_tx_0_INBUF_ENABLED 0u
#define UART_DEBUG_tx_0_INIT_DRIVESTATE 1u
#define UART_DEBUG_tx_0_INIT_MUXSEL 18u
#define UART_DEBUG_tx_0_INPUT_SYNC 2u
#define UART_DEBUG_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_tx_0_NUM 1u
#define UART_DEBUG_tx_0_PORT GPIO_PRT5
#define UART_DEBUG_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_DEBUG_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_DEBUG_tx_INBUF_ENABLED 0u
#define UART_DEBUG_tx_INIT_DRIVESTATE 1u
#define UART_DEBUG_tx_INIT_MUXSEL 18u
#define UART_DEBUG_tx_INPUT_SYNC 2u
#define UART_DEBUG_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_DEBUG_tx_NUM 1u
#define UART_DEBUG_tx_PORT GPIO_PRT5
#define UART_DEBUG_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_DEBUG_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Disconnect_LED */
#define Disconnect_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_0_INBUF_ENABLED 0u
#define Disconnect_LED_0_INIT_DRIVESTATE 1u
#define Disconnect_LED_0_INIT_MUXSEL 0u
#define Disconnect_LED_0_INPUT_SYNC 2u
#define Disconnect_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_0_NUM 3u
#define Disconnect_LED_0_PORT GPIO_PRT0
#define Disconnect_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Disconnect_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_INBUF_ENABLED 0u
#define Disconnect_LED_INIT_DRIVESTATE 1u
#define Disconnect_LED_INIT_MUXSEL 0u
#define Disconnect_LED_INPUT_SYNC 2u
#define Disconnect_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_NUM 3u
#define Disconnect_LED_PORT GPIO_PRT0
#define Disconnect_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Advertising_LED */
#define Advertising_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_0_INBUF_ENABLED 0u
#define Advertising_LED_0_INIT_DRIVESTATE 1u
#define Advertising_LED_0_INIT_MUXSEL 0u
#define Advertising_LED_0_INPUT_SYNC 2u
#define Advertising_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_0_NUM 1u
#define Advertising_LED_0_PORT GPIO_PRT1
#define Advertising_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Advertising_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_INBUF_ENABLED 0u
#define Advertising_LED_INIT_DRIVESTATE 1u
#define Advertising_LED_INIT_MUXSEL 0u
#define Advertising_LED_INPUT_SYNC 2u
#define Advertising_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_NUM 1u
#define Advertising_LED_PORT GPIO_PRT1
#define Advertising_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Hibernate_Wakeup_SW */
#define Hibernate_Wakeup_SW_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define Hibernate_Wakeup_SW_0_INBUF_ENABLED 1u
#define Hibernate_Wakeup_SW_0_INIT_DRIVESTATE 1u
#define Hibernate_Wakeup_SW_0_INIT_MUXSEL 0u
#define Hibernate_Wakeup_SW_0_INPUT_SYNC 2u
#define Hibernate_Wakeup_SW_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Hibernate_Wakeup_SW_0_NUM 4u
#define Hibernate_Wakeup_SW_0_PORT GPIO_PRT0
#define Hibernate_Wakeup_SW_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Hibernate_Wakeup_SW_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Hibernate_Wakeup_SW_DRIVEMODE CY_GPIO_DM_PULLUP
#define Hibernate_Wakeup_SW_INBUF_ENABLED 1u
#define Hibernate_Wakeup_SW_INIT_DRIVESTATE 1u
#define Hibernate_Wakeup_SW_INIT_MUXSEL 0u
#define Hibernate_Wakeup_SW_INPUT_SYNC 2u
#define Hibernate_Wakeup_SW_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Hibernate_Wakeup_SW_NUM 4u
#define Hibernate_Wakeup_SW_PORT GPIO_PRT0
#define Hibernate_Wakeup_SW_SLEWRATE CY_GPIO_SLEW_FAST
#define Hibernate_Wakeup_SW_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
